---
title: "Quality Control"
author: "D. Ford Hannum Jr."
date: "7/16/2020"
output: 
        html_document:
                toc: true
                toc_depth: 3
                number_sections: false
                theme: united
                highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(Seurat)
library(ggplot2)
library(data.table)
library(MAST)
```


```{r reading in the data}

wbm <- readRDS('./data/wbm_clustered_filtered_named.rds')

```


# Plotting Different QC Metrics by Clusters

```{r plots on plots}
VlnPlot(wbm, features = 'nFeature_RNA', split.by = 'cluster_IDs')

VlnPlot(wbm, features = 'nCount_RNA', split.by = 'cluster_IDs')

VlnPlot(wbm, features = 'percent.mt', split.by = 'cluster_IDs')

```

```{r feature plots}
FeatureScatter(wbm, feature1 = 'nCount_RNA', feature2 = 'nFeature_RNA')

FeatureScatter(wbm, feature1 = 'nCount_RNA', feature2 = 'percent.mt')

FeatureScatter(wbm, feature1 = 'percent.mt', feature2 = 'nFeature_RNA')
```

