---
title: "V2 Analysis"
author: "D. Ford Hannum Jr."
date: "5/5/2021"
output: 
        html_document:
                toc: true
                toc_depth: 3
                code_folding: hide
                number_sections: false
                theme: united
                highlight: tango
---

```{r setup, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(Seurat)
library(ggplot2)
library(data.table)
library(MAST)
library(SingleR)
library(dplyr)
library(tidyr)
library(limma)
library(scRNAseq)
library(ggpubr)
library(xlsx)
library(ComplexHeatmap)
```

# LOADING DATA

## Version 1

```{r}
wbm <- readRDS('./data/v3/mpl.migr1.121420-2.rds')
# table(wbm$Condition2)

wbm$figure.labels <- ifelse(wbm$v7.labels %in% c('MEP/MCP','MEP/ERP'),
                            ifelse(wbm$v7.labels == 'MEP/MCP', 'MkP','MEP'),
                            as.character(wbm$v7.labels))

wbm$figure.labels <- ifelse(wbm$figure.labels == 'Tcell', 'T-cell',
                            ifelse(wbm$figure.labels == 'Bcell','B-cell',
                                   ifelse(wbm$figure.labels == 'Bcell-Prog',
                                          'B-cell Prog.', wbm$figure.labels)))
wbm$UMAP1 <- wbm@reductions$umap@cell.embeddings[,1]
wbm$UMAP2 <- wbm@reductions$umap@cell.embeddings[,2]

wbm$figure.labels2 <- ifelse(wbm$figure.labels != 'MK',
                             as.character(wbm$figure.labels),
                            ifelse(wbm$UMAP1 < 0, 'MK-1','MK-2'))

wbm$figure.labels2 <- ifelse(wbm$figure.labels != 'Mono/Macro', 
                         as.character(wbm$figure.labels2),
                         ifelse(wbm$UMAP1 < -5, 'Mono/Macro-1','Mono/Macro-2'))

wbm$figure.labels <- factor(wbm$figure.labels,
                            levels = levels(as.factor(wbm$figure.labels))[c(5,3,1,2,10,9,4,6,8,7)])

Idents(wbm) <- wbm$figure.labels

# table(Idents(wbm))

mk1.cells <- rownames(wbm@meta.data[wbm$figure.labels == 'MK-1',])
mep1.cells <- rownames(wbm@meta.data[wbm$figure.labels == 'MkP',])

wbm$figure.labels3 <- ifelse(wbm$figure.labels2 %in% c('Mono/Macro-1','Mono/Macro-2'),
                             'Mono/Macro', as.character(wbm$figure.labels2))
color_pal <- c("#0072B2", "#CC79A7", "#009E73",'black',"#999999",
               "#E69F00", "#56B4E9","#D55E00", 'limegreen', 'violet')
color_pal2 <- c(color_pal, 'red')

wbm$Condition3 <- ifelse(wbm$Condition2 == 'Migr1', 'MigR1',
                         ifelse(wbm$Condition2 == 'enrMigr1', 'CD41+ enr. MigR1',
                                ifelse(wbm$Condition2 == 'Mpl', 'MPLW515L', 'CD41+ enr. MPLW515L')))

wbm$Condition3 <- factor(wbm$Condition3,
                         levels = levels(as.factor(wbm$Condition3))[c(3,4,1,2)])

wbm$Experiment <- ifelse(wbm$Condition2 %in% c('enrMigr1','Migr1'), 'MigR1','MPL')
```

## Version 2

Data was created in JunToDoList.Rmd. Further analysis comparing V2 to V1 can be found in VersionComparison.Rmd

```{r}
int <- readRDS('./data/v4/cca.integrated.rds')
DimPlot(int)
int$cross.label <- factor(int$seurat_clusters,
                        labels = c('Gran','Gran','Gran','B-cell','Gran',
                                   'Gran','Gran','MkP','Mono/Macro','Gran',
                                   'Erythroid','B-cell','MEP','T-cell','MkP',
                                   'Gran','B-cell','B-cell','Mono/Macro','B-cell Prog.',
                                   'MK-2'))

# Keeping clusters separate
int$cross.label.fine <- factor(int$seurat_clusters,
                        labels = c('G1','G2','G3','B1','G4',
                                   'G5','G6','MkP1','MM1','G7',
                                   'CMP', 'B2','G8','G9','MM2',
                                   'E','B3','MEP','T','MkP2',
                                   'G10','B4','B5','MM3','BP',
                                   'MK'))

int$cross.label.fine2 <- factor(int$cross.label.fine,
                                levels = c(paste0('G',1:10), 'CMP',
                                           paste0('MM',1:3), paste0('B',1:5),
                                           'T','BP','E','MEP','MkP1','MkP2',
                                           'MK'))

int <- RunTSNE(int, dims = )
DimPlot(int, group.by = 'cross.label.fine', repel = T, label = T) +
        ggtitle('With Fine Labels from Cross-Tabulation')
```